In [1]:
import numpy as np

In [2]:
a = np.array([1,4,-5,3])
b = np.array([3,-1,0,2])

print(a@b)
a.shape = (4,1) # a matrix with 1 column (a column vector)
b.shape = (4,1) # a matrix with 1 column (a column vector)
print(a)
print(b)
print(b.shape)
print(b.T.shape)
print(a@b.T) #it was a@b
print(a.T@b)
print(float(a.T@b))
print(a@b.T)

5
[[ 1]
 [ 4]
 [-5]
 [ 3]]
[[ 3]
 [-1]
 [ 0]
 [ 2]]
(4, 1)
(1, 4)
[[  3  -1   0   2]
 [ 12  -4   0   8]
 [-15   5   0 -10]
 [  9  -3   0   6]]
[[5]]
5.0
[[  3  -1   0   2]
 [ 12  -4   0   8]
 [-15   5   0 -10]
 [  9  -3   0   6]]


In [20]:
t = np.array([2,0,-1])
t.shape = (3,1)
np.cross(t.T, t.T) #[0,0,0]
a = np.array([-2,6,1])
a.shape = (3,1)
b = np.cross(t.T, a.T) #[6,0,12]
c = np.cross(a.T, t.T) #[-6,0,-12]
t.T@b.T #0
a.T@b.T #0

array([[0]])

In [28]:
#3d vector
def get_t_matrix(vec):
  m = np.zeros((vec.size, vec.size))
  m[0,1] = -vec[2]
  m[0,2] = vec[1]
  m[1,0] = vec[2]
  m[1,2] = -vec[0]
  m[2,0] = -vec[1]
  m[2,1] = vec[0]
  return m

m = get_t_matrix(t)
print(m.dot(t))
print(m.dot(a))

print(-m==m.T)

m2 = m.dot(m)
print(m2==m2.T)

m3 = m.dot(m.dot(m))
print(m3==m3.T)

[[0.]
 [0.]
 [0.]]
[[ 6.]
 [ 0.]
 [12.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True False  True]
 [False  True False]
 [ True False  True]]
